[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.142.0"  # 替换为你项目实际使用的 Hugo 版本

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"
